name: Poll for Submodule Changes

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  # Optionally trigger this manually if needed
  workflow_dispatch:

jobs:
  poll-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout parent repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: 'true'  # Ensure submodules are also checked out

    - name: Fetch the latest changes for submodules
      run: |
        git submodule update --remote  # Fetch the latest changes from submodule repositories
        git submodule foreach 'git fetch origin'  # Ensure submodules are updated with latest from their remote

    - name: Check for changes and update submodule references
      run: |
        git submodule status  # Check the current submodule status
        git diff --exit-code || (git add . && git commit -m "Update submodules to latest commits" && git push origin main)
        # If changes are detected, commit and push those changes to the parent repository
